config/routes.rb
Rails.application.routes.draw do
  # get 'connections/index'

  # get 'connections/show'

  devise_for :users, controllers: { registrations: 'registrations'}
  root to: 'pages#home'

  resources :musicians, only: [:index, :show] do
    member do
     get "connect", to: "musicians#connect"
     get "remove", to: "musicians#remove"
     get "block", to: "musicians#block"
     get "unblock", to: "musicians#unblock"
     get "accept", to: "musicians#accept"
    end
  end

  resources :connections, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :projects do
      resources :comments
      resources :participants, only: [:create, :destroy]
      end

  resources :conversations do
    resources :messages do
      member do
        get "mark_read", to: "messages#mark_read", as: :read
      end
    end
  end
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :user
  belongs_to :second_user, :class_name => 'User'


end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  def index
    @connections = current_user.friends
    @pending_connections = current_user.pending_friends
    # binding.pry
    authenticate_user!

  end


  # def show

  # end
end

app/views/connections/_connection_button.html.erb
  <div class="conecting">
    <% if  @musician.friends_with?(current_user) %>
      <!-- <p>You are already connected!</p> -->
      <p>
        <%= link_to remove_musician_path(@musician) do%>
          <span>Remove connection  </span><i class="fa fa-times-circle"></i>
        <% end %>
        <%elsif @musician.pending_friends.include?(current_user)%>
      <!-- <p>You are pending connection!</p> -->
      <p><%= link_to "Remove connection", remove_musician_path(@musician) , class: "btn btn-primary btn-lg" %>

      </p>
    <%elsif @musician.pending_friends.include?(current_user)%>
      <!-- <p>You are pending connection!</p> -->
      <p><%= link_to "Remove connection", remove_musician_path(@musician) , class: "btn btn-primary btn-lg" %></p>
    <%else%>
    <% if current_user != @musician %>

      <p><%= link_to "Connect", connect_musician_path(@musician) , class: "btn btn-primary btn-lg" %></p>
    <%end%>

    <%end%>
    <!-- btn block use only works if firends -->
    <% if  @musician.friends_with?(current_user) %>
      <p><%= link_to block_musician_path(@musician) do%>
  <span>Block  </span><i class="fa fas fa-ban"></i>
  <% end %></p>
    <% elsif  current_user.blocked_friends.include?(@musician) %>
    <p><%= link_to "UNBLOCK", unblock_musician_path(@musician) , class: "" %></p>
    <%end%>
  </div>

app/views/connections/index.html.erb
<div class="wrapper_connections">
<div class="container">
  <div class="row push_down">
   <div class="col-sm-8 card_friends">
      <h1>Connections</h1>
      <!-- <p>Find me in app/views/connections/index.html.erb</p> -->

      <% @connections.each do |connection|%>
     <!--  <p><%= connection.first_name %> <%= connection.last_name %></p> -->
     <%= link_to musician_path(connection) do  %>
      <%= cl_image_tag connection.avatar, width: 70, height: 70, crop: :fill, class: "avatar_connection"  %>
     <% end %>
     <% end %>


     <% if @pending_connections.size > 0 %>
      <h3>Your pending connections:</h3>

      <% @pending_connections.each do |pending_connection|%>
    <!--   <p><%= pending_connection.first_name %> <%= pending_connection.last_name %></p> -->
       <%= link_to musician_path(pending_connection) do  %>
      <%= cl_image_tag pending_connection.avatar, width: 70, height: 70, crop: :fill, class: "avatar_connection"  %>
      <% end %>
      <p><%= link_to "Accept connection", accept_musician_path(pending_connection) , class: "btn btn-primary btn-lg" %></p>
      <% end %>

      <% end %>
    </div>
  </div>
</div>
</div>