config/routes.rb
Rails.application.routes.draw do
  # get 'connections/index'

  # get 'connections/show'

  devise_for :users, controllers: { registrations: 'registrations'}
  root to: 'pages#home'

  resources :musicians, only: [:index, :show] do
    member do
     get "connect", to: "musicians#connect"
     get "remove", to: "musicians#remove"
     get "block", to: "musicians#block"
     get "unblock", to: "musicians#unblock"
     get "accept", to: "musicians#accept"
    end
  end

  resources :connections, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :projects do
      resources :comments
      resources :participants, only: [:create, :destroy]
      end

  resources :conversations do
    resources :messages do
      member do
        get "mark_read", to: "messages#mark_read", as: :read
      end
    end
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id
    scope :between, -> (sender_id,recipient_id) do
      where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
   end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
   @users = User.all
   @conversations = Conversation.all
   @conversation = Conversation.last
   @message = Message.new
  end

  def show
    @conversation = Conversation.find(params[:sender_id],params[:recipient_id])
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
     @conversation = Conversation.between(params[:sender_id],
       params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

  def destroy
    @conversation = Conversation.find(params[:id])
    @conversation.destroy
    redirect_back(fallback_location: root_path)
  end


  private

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

end

app/views/conversations/index.html.erb
<div class="container">
  <div class="row push_down margin_down">
    <div class="col-sm-4">
      <div class="ui segment">
        <h3>Conversations</h3>
        <div class="ui list">
          <% @conversations.each do |conversation| %>
            <% if conversation.sender_id == current_user.id %>
              <% recipient = User.find(conversation.recipient_id) %>
            <% else %>
              <% recipient = User.find(conversation.sender_id) %>
            <% end %>
            <div class="item">
              <%= link_to recipient.first_name + " " + recipient.last_name, conversation_messages_path(conversation)%>
              <%= link_to "Delete", conversation_path(conversation), class: "btn btn-sm btn-hover btn-primary", method: :delete,
              data: { confirm: "Are you sure you want to delete conversation?" } %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="ui segment">
        <h3>All Users</h3>
          <div class="ui list">
            <% @users.each do |user| %>
              <% if user.id != current_user.id %>
            <div class="item">
              <%= user.first_name + " " + user.last_name %> <%= link_to 'Message me!', conversations_path(sender_id: current_user.id,recipient_id: user.id), method: 'post'%>
            </div>
              <% end %>
            <% end %>
          </div>
      </div>
    </div>
    <div class="col-sm-8">
      <%= render "messages/replay-form", locals: {conversation: @conversation, message: @message} %>
    </div>
  </div>
</div>
<br>