config/routes.rb
Rails.application.routes.draw do
  # get 'connections/index'

  # get 'connections/show'

  devise_for :users, controllers: { registrations: 'registrations'}
  root to: 'pages#home'

  resources :musicians, only: [:index, :show] do
    member do
     get "connect", to: "musicians#connect"
     get "remove", to: "musicians#remove"
     get "block", to: "musicians#block"
     get "unblock", to: "musicians#unblock"
     get "accept", to: "musicians#accept"
    end
  end

  resources :connections, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :projects do
      resources :comments
      resources :participants, only: [:create, :destroy]
      end

  resources :conversations do
    resources :messages do
      member do
        get "mark_read", to: "messages#mark_read", as: :read
      end
    end
  end
end

app/views/shared/_banner.html.erb
<div class="banner" >
  <div class='slide1' style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_url('photo-band.png') %>)">
  </div>

  <div class='slide2' style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_url('photo-singer.jpeg') %>)">
  </div>

  <div class='slide3' style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%),  url(<%= image_url('concert.png') %>)">
  </div>

  <div class="banner-content">
    <h1>CONNECTING MUSICIANS</h1>
    <h3>Don’t dream it, play it!</h3>

    <%= render 'shared/search_bar' %>

  </div>


</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag "logo_nsemble_editable.png", height: 50 %>
    <% end %>
  </div>
  <div class="footer-links ">
    <a href="#"><i class="fa fa-facebook-f"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
  </div>
  <div class="footer-grid-block footer-links">
    <ul class="">
      <li><a href="#">Contact</a></li>
      <li><%= link_to "Meet the team"%></li>
      <li><a href="#">Terms &amp; Conditions</a></li>
      <li><a href="#">FAQ</a></li>
    </ul>
  </div>


  <div class="footer-copyright">
    &copy; 2018 Nsemble. All rights reserved.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_nsemble_editable.png", height: 50 %>
  <% end %>

<!--I've commented the "unless" statement beacuse I wasted the search bar to be everywhere for now (Aron) -->

<div>
  <%= render 'shared/search_bar' unless url_for == root_path %>
</div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>


      <!-- Links when logged in -->


      <%= link_to "CREATE A PROJECT", new_project_path, class: "navbar-wagon-item navbar-wagon-link" %>



      <%= link_to connections_path, class: "navbar-wagon-item navbar-wagon-link"  do%>
        <i class="fa fa-users"></i>
        <% if current_user.pending_friends.length > 0 %>
          <span><%= current_user.pending_friends.length %></span>
          <% end%>
        <% end %>

      <%= link_to conversations_path, class: "navbar-wagon-item navbar-wagon-link"  do%>
        <i class="fa fa-envelope"></i>
        <span><%= Message.where.not(user: current_user).where(read: false).count %></span>
      <% end %>



      <%= link_to destroy_user_session_path, class: "navbar-wagon-item navbar-wagon-link", method: :delete do%>
          <i class="fa fa-sign-out"></i>
      <% end %>

      <%#= link_to "Log out", destroy_user_session_path,class: "navbar-wagon-item navbar-wagon-link",  method: :delete %>



      <!-- <!-- a: position: relative;

      span: {
    position: absolute;
    top: -5px;
    right: 18px;
    font-size: 0.8em;
    color: #bcbcbc;
    font-weight: bold;
  -->


      <%#= link_to "Connection requests: #{current_user.pending_friends.length}", connections_path, class: "navbar-wagon-item navbar-wagon-link"%>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%#= image_tag (current_user.avatar), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

            <%= link_to musician_path(current_user) do  %>
                <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu" %>
            <% end %>


          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>

          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<!-- old serchbar -->

<%#= form_tag musicians_path, method: :get, class: "form-inline" do%>
  <%#= text_field_tag :skill,
    params[:query],
    class: "form-control form-control-lg",
      placeholder: "What? ex: Drummer, Project..."
      %>
  <%#= text_field_tag :location,
    params[:query],
    class: "form-control search",
      placeholder: "Ex: Amsterdam"
      %>
  <%#= submit_tag "Find", class: "btn btn-primary" %>
<%# end %>

<!-- new serchbar (davis) -->
<div id="custom-search-input">
  <form class="form-inline" action="/musicians" accept-charset="UTF-8" method="get">
    <div class="search-bar">
      <input type="search" name="location" id="location" class="form-control form-control-lg" placeholder="Search">
        <button class="btn btn-default">
            <span class=" glyphicon glyphicon-search icon-move"></span>
        </button>
    </div>
  </form>
</div>