config/routes.rb
Rails.application.routes.draw do
  # get 'connections/index'

  # get 'connections/show'

  devise_for :users, controllers: { registrations: 'registrations'}
  root to: 'pages#home'

  resources :musicians, only: [:index, :show] do
    member do
     get "connect", to: "musicians#connect"
     get "remove", to: "musicians#remove"
     get "block", to: "musicians#block"
     get "unblock", to: "musicians#unblock"
     get "accept", to: "musicians#accept"
    end
  end

  resources :connections, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :projects do
      resources :comments
      resources :participants, only: [:create, :destroy]
      end

  resources :conversations do
    resources :messages do
      member do
        get "mark_read", to: "messages#mark_read", as: :read
      end
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :picture, PhotoUploader

  has_many :participants, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :location, presence: true


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      sql_query = "title ILIKE :query OR location ILIKE :query"
      @projects = Project.where(sql_query, query: "%#{params[:query]}%")
    else
      @projects = Project.all
    end

    # @projects = Project.where.not(latitude: nil, longitude: nil)

    # @markers = @projects.map do |project|
    #   {
    #     lat: project.latitude,
    #     lng: project.longitude,
    #     infoWindow: { content: render_to_string(partial: "/projects/map_box", locals: { project: project }) }
    #   }
    # end
  end

  def show
    @project = Project.find(params[:id])
    @participants = @project.participants
    @comments = @project.comments
    @comment = Comment.new

  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.user != current_user
      flash[:alert] = "You can not edit this project"
      redirect_to @project
    else
      if @project.update(project_params)
        flash[:alert] = "Your project has been successfully updated"
        redirect_to @project
      else
        render :edit
        render json: @project.errors
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.user != current_user
      flash[:alert] = "You can not delete this project"
      redirect_to @project
    else
      if @project.destroy
        flash[:alert] = "Your project has been deleted"
        redirect_to projects_path
      else
        render :show
        render json: @project.errors
      end
    end
  end




  private

  def project_params
    params.require(:project).permit(:title, :description, :location, :start_time, :end_time, :picture)
  end

end

app/views/projects/_cards.html.erb
 <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script> -->
  <!-- MiniPreview stuff here -->
  <!-- <script type="text/javascript"> -->
   <!--  $(function() {
                $('#ccc a').miniPreview({ prefetch: 'pageload' });
            }); -->
  <!-- </script> -->

<div class="container card-container">
  <div class="row">
    <% @projects.each do |project| %>
      <div class="col-xs-12 col-sm-4 card-box card-box-project zoom">
        <%= link_to project_path(project), class: "card-link" do%>
        <div id="ccc" class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= cl_image_path(project.picture)%>');">

        </div>
        <% end %>
        <div class="card-description">
            <h2 class="description"><%= project.title.capitalize %></h2>
            <p class="instrument-card"><%= project.location.upcase %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>







<!-- <%#= link_to musician_path(@project.user) do  %>
      <li ><%#= cl_image_tag @project.user.avatar, width: 100, height: 100, crop: :fill , class: "participant"  %>

      </li>
      <%# end %>
 -->

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
    <%= f.input :title, placeholder: "What is your project about?" %>
    <%= f.input :description, placeholder: "Add a description to your project...", as: :text %>
    <%= f.input :start_time, placeholder: "Start Time" %>
    <%= f.input :end_time, placeholder: "End Time" %>
    <%= f.input :location, placeholder: "Where?" %>
    <%= f.input :picture %>
    <%= f.input :picture_cache, as: :hidden %>

    <%= f.button :submit, class: "btn btn-primary"  %>
<% end %>




<!-- create_table "projects", force: :cascade do |t|
    t.string "title"
    t.string "description"
    t.string "picture"
    t.datetime "start_time"
    t.datetime "end_time"
    t.string "location"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "user_id"
    t.index ["user_id"], name: "index_projects_on_user_id"
  end
 -->

app/views/projects/_message.html.erb
<div class="message">
  <img class="avatar-large" src="https://kitt.lewagon.com/placeholder/users/gabriel-dehan">
  <div class="message-name">
    <h3>Gab Dehan</h3>
    <p>10/07/17</p>
  </div>
  <div class="message-body">
    <p><strong>I am not sure yet!</strong></p>
    <p>
      <%= @comment.content %>
    </p>
  </div>
  <div class="message-status">
    <p class="status pending">Pending</p>
    <p class="price">€345</p>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <div class="row margin_up">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Edit your project</h1>
      <%= render 'form' %>
      <%= link_to 'Back to projects', projects_path %>
      <br>
      <br>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<h1 class="text-center">This are the projects that you can enjoy:
</h1>




<%= render 'projects/cards' %>


<!-- <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
></div>
 -->

app/views/projects/new.html.erb
<div class="container">
  <div class="row margin_up">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Create a project</h1>
      <%= render 'form' %>
      <br>
    <!--   <%#= link_to 'Back to project', project_path(@project) %> -->
      <br>
      <br>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<!-- Header with Background Image -->
<div class="wrapper">
<div class="banner banner-project" style="background-image: linear-gradient(-225deg, rgba(25,25,25,0.6) 0%, rgba(178,12,12,0.6) 98%),url('<%= cl_image_path(@project.picture) %>')">

</div>

    <!-- Page Content -->
    <div class="content-projects">
      <div class="project-left">
      <div class="project-background">
        <%= cl_image_tag @project.picture, width: 350, height: 350, crop: :fill, class: "project-picture"  %>

        <div class="project-content">
         <h2 class="mt-4"><%= @project.title.upcase %></h2>
         <p><%= @project.description %></p>

         <h2 class="mt-4">WHEN/ WHERE</h2>

          <p><span class="tipo-grey">STARTS AT</span>  <%= @project.start_time.to_formatted_s(:long_ordinal) %></p>
          <p><span class="tipo-grey">ENDS AT</span>  <%= @project.end_time.to_formatted_s(:long_ordinal) %></p>
          <p><span class="tipo-grey">LOCATION</span>  <%= @project.location %></li>
          <!-- <li><%= cl_image_tag(@project.user.avatar) %></li> -->

      </div>
      </p>

      <% if current_user == @project.user %>
      <p>
        <%= link_to edit_project_path(@project) do%>
          <span>Edit Project  </span><i class="fa fa-edit"></i>
          <% end %>

        <br>
        <%= link_to project_path(@project), method: :delete, data: { confirm: "Are you sure?" } do%>
          <span>Delete Project  </span><i class="fa fa-trash"></i>
          <% end %>
        <% else %>




        <p><%= link_to "Join the project", project_participants_path(@project) , method: :post, class: "btn btn-primary btn-lg" %></p>
        <% end %>

       </div>
        <div class="map">
        <%= image_tag "map_fake.jpg", width: 390, height: 390, crop: :fill%>
        </div>
      </div>

      <div class="project-right">
         <p class="tipo-project">NSEMBLE PEOPLE</p>
         <div>
          <%= link_to musician_path(@project.user) do  %>

            <%= cl_image_tag @project.user.avatar, width: 100, height: 100, crop: :fill , class: "participant"  %>
            <% end %>

          <% @participants.each do |participant| %>
          <%= link_to musician_path(participant.user) do  %>


            <%= cl_image_tag participant.user.avatar, width: 100, height: 100, crop: :fill , class: "participant" %>


          <% end %>
          <% end %>
          </div>


        <%= render 'comments/form' %>

          <% @comments.each do |comment| %>
            <div class="comment">
              <%= cl_image_tag comment.user.avatar, width: 60, height: 60, crop: :fill, class: "comment-avatar"%>


               <div class="comment-content">
                <p>
                  <%= comment.content%>
                </p>
               </div>

              <div >
                <p class="tipo-grey"><%=comment.user.first_name%> <%=comment.user.last_name%></p>
                <p class="tipo-grey"><%=comment.created_at.to_formatted_s(:short) %></p>
              </div>
            </div>
          <% end %>

        <!--  <p><%#= link_to "Back to projects", projects_path %></p> -->


      </div>
    </div>
    </div>